### ISSUE TITLE
messy code

### ISSUE THREAD

**Issue by platonev** [Dronecode/MAVProxy#113]
Hello, I am using the MAVProxy to control my arducopter, but there is always received messy code, while my workmate can received the correct message, I want some help, thanks!

**Comment by rmackay9** [comment]
That's probaly a baud rate problem.  I guess you're seeing all kinds of crazy characters displayed in the console which is most commonly a baud rate mismatch between what the vehicle (or radio) is sending and what MAVProxy is expecting.

**Comment by platonev** [comment]
Oh, thanks, it surely because this. it should be 57600, but i used the 115200 before.
