### ISSUE TITLE
Add a note on how to set the baud rate from running MAVProxy

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/MAVProxy#172]
We document how to specify the baudrate for a serial connection when starting MAVProxy but not when it is running - which is a problem on windows when you're starting mavproxy from double-click.

It would be good to add a note on how to do this, minimally in http://tridge.github.io/MAVProxy/link.html

Tridge suggested that calling ``set baudrate XXXXX`` before using link add is probably the easiest way. It would also be useful to show the syntax for adding with link add, and also make it clear that the default baud rate is 57600

**Comment by stephendade** [comment]
Fixed in #180

**Comment by stephendade** [comment]
Also, the documentation is actually at http://dronecode.github.io/MAVProxy/  :)

**Comment by hamishwillee** [comment]
Thanks Stephen

1. Change looks good to me but is not yet live
2. Tridge version is still live, and is what gets hit when I do a search on google - perhaps get him to remove it?

**Comment by stephendade** [comment]
Changes live now.
