### ISSUE TITLE
Mavproxy Installation Instructions Modification

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/MAVProxy#190]
This is cross posted from https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/135

I've noticed that the default set of packages listed to install on Linux for MavProxy doesn't include python-dev which is required for some systems (raspberry pi at a minimum)

Suggest it gets added to the list of packages to apt-get install alongside the existing ones so that people don't miss out.

Cheers
Ben

**Comment by stephendade** [comment]
Done in #204!
