### ISSUE TITLE
Mac instructions (only) install droneapi

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/MAVProxy#205]
http://dronecode.github.io/MAVProxy/html/getting_started/download_and_installation.html#mac is about droneapi not mavproxy

> Install DroneKit-Python and its remaining dependencies (including MAVProxy) from the public PyPi repository:

  ```
sudo pip install numpy pyparsing
sudo pip install droneapi

**Comment by stephendade** [comment]
Fixed in #210

**Comment by hamishwillee** [comment]
Thanks. Looks good.
