### ISSUE TITLE
In code block you don't need windows double slashes

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/MAVProxy#206]
See (for example) http://dronecode.github.io/MAVProxy/html/development/mavdevenv.html

> Use pip to install the other packages:

   ```
cd C:\\Python27\\Scripts
pip install pyinstaller
```

The double slashes are appearing above in the rendered output. Double backslashes should not be used in code blocks, but should be used outside of code blocks.

**Comment by stephendade** [comment]
Fixed in #210

**Comment by hamishwillee** [comment]
Thanks, looks good.
