### ISSUE TITLE
Image Processing with cuav - Image source

### ISSUE THREAD

**Issue by Georacer** [Dronecode/MAVProxy#211]
URL: ../cuav_module/index
Title: Image Processing with cuav

This isn't an urgent request or fix - I'd just like to see this documentation as complete as possible. It's a really nice tool.

So, I'd like to see more documentation on the image source for the cuav. Is it a folder? Is it a ttyUSB* camera?

Thanks.

**Comment by stephendade** [comment]
The image source is a USB camera for the "live" version. There's also an offline version of cuav that works with folders and flight logs.
I'll have to look carefully through the code to find out which cameras the online version works with and the specific file/folder structure required for the offline version.

**Comment by stephendade** [comment]
Issue partly fixed now in #213 . I've put in information for camera compatibility. Still need to look at the folder source.

**Comment by Georacer** [comment]
Nice. This clearly communicates the hardware requirements. Thanks!

**Comment by Georacer** [comment]
If cuav will not support pulling images from a folder any time soon, I consider this issue closed. Shall I?

**Comment by stephendade** [comment]
Correct. Currently you only only use folders when running cuav offline.

It's on the long-term todo list to explain how to do that.
