### ISSUE TITLE
map: old ADS-B tracks are not cleared when threat is gone

### ISSUE THREAD

**Issue by SamuelDudley** [Dronecode/MAVProxy#230]
Tracks build up over time when running SITL with ADS-B enabled.
![screenshot from 2015-11-27 19 52 20](https://cloud.githubusercontent.com/assets/8290680/11443038/b6430c64-9569-11e5-85d3-1ff47836a64f.png)

**Comment by tridge** [comment]
fixed with your PR, thanks!
