### ISSUE TITLE
Examples - Baudrate example are not the same

### ISSUE THREAD

**Issue by khancyr** [Dronecode/MAVProxy#239]
URL: ../getting_started/examples
Title: Examples  Baudrate example are not the same

Just a typo fix . 

Run MAVProxy in daemon mode, taking in a radio link (COM17 at **9600** kbps) and outputting it to the local network. This allows a single instance of MAVProxy to distribute the telemetry stream to multiple clients:

mavproxy.py --master=COM17,**57600** --out=udpin:0.0.0.0:14550 --daemon

**Comment by stephendade** [comment]
Fixed in #245 Thanks!
