### ISSUE TITLE
Startup Options - Num-cell missing

### ISSUE THREAD

**Issue by khancyr** [Dronecode/MAVProxy#240]
URL: ../getting_started/starting
Title: Startup Options

According to the doc, we got --num-cells option (https://dronecode.github.io/MAVProxy/html/getting_started/starting.html#num-cells) 
But it didn't seem to exist anymore (https://github.com/Dronecode/MAVProxy/blob/master/MAVProxy/mavproxy.py#L832)

So we get : 
````
mavproxy.py: error: no such option: --num-cells

**Comment by stephendade** [comment]
Fixed in #245
