### ISSUE TITLE
Development Environment - Visual studio setup

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/MAVProxy#251]
URL: ../development/mavdevenv
Title: Development Environment

Visual Studio Setup section - the content is good, but would be good to clarify exactly what this setup "does" (ie. what does it mean to "build mavproxy"). Something along the lines of "This section shows how you can create a Windows MAVProxy installer file that includes OpenCV, etc etc." (assuming that is what building means)

**Comment by stephendade** [comment]
Updated! Should be clearer now.

**Comment by hamishwillee** [comment]
So "Visual Studio can be used to develop MAVProxy on Windows platforms."?  Sounds good to me. 

FYI, for some reason I can no longer see docs sources.
