### ISSUE TITLE
Startup Options - 

### ISSUE THREAD

**Issue by trondhindenes** [Dronecode/MAVProxy#255]
URL: ../getting_started/starting
Title: Startup Options

The valid parts of a connection string should be documented. Such as
tcp:127.0.0.1:5760
udp:
...etc

**Comment by stephendade** [comment]
Fixed in commit abc50fb9cc9a1f95c8fc8943fd41599bd412f98e

Thanks!

**Comment by trondhindenes** [comment]
Great stuff, much clearer now.
