### ISSUE TITLE
Startup Options - out

### ISSUE THREAD

**Issue by trondhindenes** [Dronecode/MAVProxy#273]
URL: ../getting_started/starting
Title: Startup Options

The option "tcpin" should be documented, as it's a powerful feature. It allows users to connecto to MavProxy in the same manner as a direct connection to a SITL instance (over a bound tcp port). I was shocked when I realized the code was there to support it but an undocumented feature.

**Comment by stephendade** [comment]
Fixed in 7dc314d59bbd3f3339cf36f9ded146e2d375fe08.
