### ISSUE TITLE
add lxml to the list of dependencies

### ISSUE THREAD

**Issue by kralo** [Dronecode/MAVProxy#282]
Sorry, I don't have any clue about dependency management.

The parameter module can load xml-file "blueprints" of the parameters, I guess.
However, to process these it needs lxml which is installable via pip ( `pip install lxml` )

**Comment by stephendade** [comment]
Good timing! I was just fixing up the documentation. Turns out it's better to advise the user to do an "apt-get install python-lxml" to ensure any pre-requisites are downloaded too. Fixed in d1897c8baad170630a35cb3a4cc689a3a2dc642b
