### ISSUE TITLE
sudo apt-get install python-dev missing from quickstart page

### ISSUE THREAD

**Issue by bobotus** [Dronecode/MAVProxy#286]
URL: ../getting_started/download_and_installation
Title: Download and Installation

Page missing python-dev pakage from linux quickstart. Can't install/compile mavproxy with pip without it.

After installing python-dev also had this error in pip, but mavproxy still seems to be working:
Compiling /tmp/pip-build-mACxcs/pyserial/serial/aio.py ...
  File "/tmp/pip-build-mACxcs/pyserial/serial/aio.py", line 366
    def open_serial_connection(*,
                                ^
SyntaxError: invalid syntax

**Comment by gmorph** [comment]
I found a similar thing.  It will be fixed in this PR
https://github.com/Dronecode/MAVProxy/pull/288
Thanks, Grant.
