### ISSUE TITLE
MAVProxy Wifi Bridge - Should probably add "chmod +x"

### ISSUE THREAD

**Issue by bobotus** [Dronecode/MAVProxy#287]
URL: ../getting_started/mavbridge
Title: MAVProxy Wifi Bridge

Should add to :
sudo chmod +x /etc/init.d/mavgateway

Otherwise this happens:
sudo chown root:root /etc/init.d/mavgateway
sudo update-rc.d mavgateway defaults
insserv: script mavgateway is not an executable regular file, skipped!

ps. thanks for the great documentation/wiki!

**Comment by stephendade** [comment]
Thanks! Fixed in  cb01be5
