### ISSUE TITLE
Windows Installer is out of date

### ISSUE THREAD

**Issue by magicrub** [Dronecode/MAVProxy#289]
as of June 14, 2016, the latest Windows binary is 1.4.40 but pip install will get you 1.5.0. This is especially bad because mavlink packet ADSB_VEHICLE has a new CRC and is not getting processed.

**Comment by stephendade** [comment]
I'm working on it. Should be done within the next week.

**Comment by magicrub** [comment]
Great, thanks!

**Comment by magicrub** [comment]
I've tested an installer that @stephendade has given me and it works great. Should hit normal download location soon

**Comment by stephendade** [comment]
Done. Firmware at http://firmware.ardupilot.org/Tools/MAVProxy/
